apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: charts/kube-prometheus-stack
      sourceRef:
        kind: GitRepository
        name: j6nca-charts
        namespace: flux-system
      version: 56.9.0
  interval: 1m0s