apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: tools
spec:
  chart:
    spec:
      chart: charts/external-secrets
      sourceRef:
        kind: GitRepository
        name: j6nca-charts
        namespace: flux-system
      version: 0.9.13
  interval: 1m0s