apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm/grafana
      sourceRef:
        kind: GitRepository
        name: j6nca-charts
        namespace: flux-system
      version: 7.3.2
  interval: 1m0s