apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: j6nca-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/j6nca/helm-charts
  ref:
    branch: main
